data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  build: docker/database
  volumes_from:
    - data
  ports:
    - "5432:5432"
